---

- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest  
    force_apt_get: yes
  become: yes
  become_method: sudo

- name: Install required system packages
  apt: 
    name: "{{ item }}"
    state: latest
    update_cache: yes 
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'gnupg-agent', 'python3-pip', 'virtualenv', 'python3-setuptools']
  become: yes
  become_method: sudo

- name: Add Docker GPG apt Key
  apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  become: yes
  become_method: sudo

- name: Add Docker Repository
  apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
  become: yes
  become_method: sudo

- name: Update apt and install docker-ce
  apt:  
    name: "{{ item }}"
    state: latest
  loop: ['docker-ce', 'docker-ce-cli', 'containerd.io']
  become: yes
  become_method: sudo
